package v1

import (
	"github.com/go-playground/validator/v10"
)

// Code generated by generator; DO NOT EDIT.

func (o *Foo) ValidateStruct(v *validator.Validate) error {
	return v.Struct(o)
}

func (o *SubFoo) ValidateStruct(v *validator.Validate) error {
	return v.Struct(o)
}
